//! Raw FFI bindings to amerkoleci/joltc (Jolt Physics C wrapper).
//! Generated by bindgen from joltc.h.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
